version: '3.8'

services:
  #--- Servicio de la Base de Datos (PostgreSQL) ---
  kong-db:
    image: postgres:13
    container_name: kong-db
    environment:
      - POSTGRES_DB=kong
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=kongpass
    networks:
      - kong-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kong -d kong"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
    volumes:
      - kong_db_data:/var/lib/postgresql/data

  #--- Servicio para preparar la Base de Datos de Kong (Migración) ---
  kong-migrations:
    image: kong:3.4 # Usa una versión específica de Kong
    container_name: kong-migrations
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-db
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kongpass
      - KONG_PASSWORD=supersecretadminpassword # Opcional: para proteger el Admin API
    depends_on:
      kong-db:
        condition: service_healthy
    command: "kong migrations bootstrap"
    networks:
      - kong-net
    restart: on-failure

  #--- Servicio Principal de Kong Gateway ---
  kong-gateway:
    image: kong:3.4
    container_name: kong-gateway
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-db
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kongpass
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=http://localhost:8002 # Opcional: para la GUI de Konga
    depends_on:
      kong-migrations:
        condition: service_completed_successfully
    networks:
      - kong-net
    ports:
      # Puerto proxy por donde pasarán las peticiones de los clientes
      - "8000:8000"
      # Puerto proxy SSL
      - "8443:8443"
      # Puerto de la API de Administración de Kong
      - "8001:8001"
      # Puerto de la GUI de Administración (si la usas)
      - "8002:8002"
    healthcheck:
      test: ["CMD-SHELL", "kong health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

#--- Definición de la Red y el Volumen ---
networks:
  kong-net:
    driver: bridge

volumes:
  kong_db_data: